# Generated by Django 2.2.3 on 2019-07-14 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('store', models.CharField(max_length=100)),
                ('items', models.IntegerField()),
                ('total', models.FloatField()),
                ('location', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('date',),
            },
        ),
    ]
