# Generated by Django 2.2.3 on 2019-07-21 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0002_auto_20190721_2237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='items',
        ),
    ]
