# Generated by Django 2.2.3 on 2019-08-04 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0005_auto_20190804_2022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='address2',
        ),
    ]
